# Motion planning request to the global planner
moveit_msgs/MotionPlanRequest request
---
# Motion planning response from the global planner
moveit_msgs/MotionPlanResponse response
---
# Feedback about the currently running global planning operation
string feedback
