# A list of motion commands with one for each section of the sequence
MotionSequenceRequest request

# Planning options
PlanningOptions planning_options
---

# Response of the request containing informaiton on all sections of the sequence
MotionSequenceResponse response

---

# The internal state that the move group action currently is in
string state
