# A list of motion commands
MotionSequenceRequest request

# Planning options
PlanningOptions planning_options
---

MotionSequenceResponse response

---

# The internal state that the move group action currently is in
string state
