# Define the frame for the specified waypoints
Header header

# The start at which to start the Cartesian path
RobotState start_state

# Mandatory name of group to compute the path for
string group_name

# Optional name of IK link for which waypoints are specified.
# If not specified, the tip of the group (which is assumed to be a chain)
# is assumed to be the link
string link_name

# A sequence of waypoints to be followed by the specified link,
# while moving the specified group, such that the group moves only
# in a straight line between waypoints
geometry_msgs/Pose[] waypoints

# The maximum distance (in Cartesian space) between consecutive points
# in the returned path. This must always be specified and > 0
float64 max_step

# If jump_threshold set above 0 then it acts as a scaling factor that is
# used to filter out large relative jumps in the generated Cartesian path
# before it is returned. The average joint-space distance between consecutive
# points in the trajectory is computed. If any individual joint-space motion
# delta is larger then this average distance by a factor of
# jump_threshold_factor, then this step is considered a jump and the returned
# path is truncated just before the jump.
float64 jump_threshold

# If prismatic_jump_threshold or revolute_jump_threshold is set > 0 then for
# each active, the joint-space difference between consecutive waypoints is
# computed and compared to the absolute threshold: prismatic_jump_threshold
# for prismatic joints and revolute_jump_threshold for revolute joints. If
# these thresholds are exceeded, then this step is considered a jump and the
# returned path is truncated just before the jump.
float64 prismatic_jump_threshold
float64 revolute_jump_threshold

# Set to true if collisions should be avoided when possible
bool avoid_collisions

# Specify additional constraints to be met by the Cartesian path
Constraints path_constraints

---

# The state at which the computed path starts
RobotState start_state

# The computed solution trajectory, for the desired group, in configuration space
RobotTrajectory solution

# If the computation was incomplete, this value indicates the fraction of the path
# that was in fact computed (number of waypoints traveled through)
float64 fraction

# The error code of the computation
MoveItErrorCodes error_code
