# Name of the planning pipeline, uses default if empty
string pipeline_id

# Name of planning config
string planner_config

# Optional name of planning group (return global defaults if empty)
string group

---

# parameters as key-value pairs
PlannerParams params
