# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: pre-release

on:
  workflow_dispatch:
  push:

jobs:
  default:
    strategy:
      fail-fast: false
      matrix:
        distro: [noetic]

    env:
      # https://github.com/ros-industrial/industrial_ci/issues/666
      BUILDER: catkin_make_isolated
      ROS_DISTRO: ${{ matrix.distro }}
      PRERELEASE: true
      BASEDIR: ${{ github.workspace }}/.work

    if: github.event_name == 'workflow_disptach' # only allow manual triggering
    name: "${{ matrix.distro }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: industrial_ci
        uses: ros-industrial/industrial_ci@master
